[tool.poetry]
name = "webui"
version = "0.1.0"
description = ""
authors = ["ethan shi <ethan.shi@gempoll.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
gradio = "^4.44.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
